version: '3'

services:

  nginx:
    build:
      context: ./docker/
      dockerfile: nginx.docker
    volumes:
      - ./src:/src
    depends_on:
      - php-fpm
    ports:
      - 8000:80

  php-fpm:
    build:
      context: ./docker/
      dockerfile: php-fpm.docker
    volumes:
      - ./src:/src
